variable "vpc_cidr" {}
variable "subnet1_cidr" {}
variable "public_subnet_az" {}
variable "subnet2_cidr" {}
variable "private_subnet_az" {}
variable "kms_alias_name" {}
variable "iam_RDS-monitoring_policy" {}
variable "alarm_name_CPU" {}
variable "alarm_name_storage" {}
variable "metric_name_cpu" {}
variable "metric_name_storage" {}
variable "instance_class" {}
variable "engine" {}
variable "engine_version" {}
variable "username" {}
variable "password" {}
variable "sns_endpoint" {}